export const SKILLS_COLLECTION = [
   { value: 'Flutter', count: 5 },
   { value: 'Dart', count: 45 },
   { value: 'Java', count: 15 },
   { value: 'Git', count: 66 },
   { value: 'Github', count: 66 },
   { value: 'Gitlab', count: 66 },
   { value: 'Agile', count: 100 },
   { value: 'Notion', count: 30 },
   { value: 'Jira', count: 60 },
   { value: 'Insomnia', count: 50 },
   { value: 'Postman', count: 50 },
   { value: 'HTML5', count: 50 },
   { value: 'CSS3', count: 50 },
   { value: 'Javascript', count: 70 },
   { value: 'Typescript', count: 35 },
   { value: 'Reactjs', count: 80 },
   { value: 'Nextjs', count: 90 },
   { value: 'Vercel', count: 50 },
   { value: 'Antd', count: 100 },
   { value: 'Bootstrap', count: 60 },
   { value: 'Apollo', count: 30 },
   { value: 'MySQL', count: 50 },
   { value: 'PostgreSQL', count: 50 },
   { value: 'Nodejs', count: 30 },
   { value: 'Nestjs', count: 40 },
]
